server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Routing Angular (SPA - Single Page Application)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend Spring Boot
    # Equivalent de pathRewrite: "^/api": "" dans proxy.conf.json
    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}